# This is a basic workflow to help you get started with Actions
name:  Notify to Discord
# Controls when the workflow will run
on:
  push:
    branches:
      - main
      - develop
      - experimental
      - master
      - secret
      - fix-thingy
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  buildWindows:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # The name of the job
    name: discod
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Send Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@master
      with:
        args: 'The project {{ EVENT_PAYLOAD.repository.full_name }} has been deployed.'
